name: example
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ionicons: ^0.2.1
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.0+2
  flutter_otp_text_field: ^1.1.1
  google_fonts: ^5.1.0
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  path_provider_android: 2.0.27

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0


  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/places/
    - assets/icons/
    - assets/
