// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKcojoI5zxuzbD08Gvuf2JVbGRZzCifs4',
    appId: '1:528499133764:web:c75d5b08c3e86c1b105b11',
    messagingSenderId: '528499133764',
    projectId: 'eksplormoris',
    authDomain: 'eksplormoris.firebaseapp.com',
    storageBucket: 'eksplormoris.appspot.com',
    measurementId: 'G-22P03LJF6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdPPFZ82ZEcXLedfyp44o7ENMpwoabekw',
    appId: '1:528499133764:android:88c0489b6c211fbb105b11',
    messagingSenderId: '528499133764',
    projectId: 'eksplormoris',
    storageBucket: 'eksplormoris.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk0wg7OOSDTBdZ8J5iaG0Rdlw8wVJ51qk',
    appId: '1:528499133764:ios:0a646fba074128ec105b11',
    messagingSenderId: '528499133764',
    projectId: 'eksplormoris',
    storageBucket: 'eksplormoris.appspot.com',
    iosClientId: '528499133764-fjivq8th1lnc8ljldilm1vv3pu1rvnfv.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk0wg7OOSDTBdZ8J5iaG0Rdlw8wVJ51qk',
    appId: '1:528499133764:ios:0f1342052aa297dd105b11',
    messagingSenderId: '528499133764',
    projectId: 'eksplormoris',
    storageBucket: 'eksplormoris.appspot.com',
    iosClientId: '528499133764-6jn6n7pcteje6jdh6pvie61k5ef9putu.apps.googleusercontent.com',
    iosBundleId: 'com.example.example.RunnerTests',
  );
}
