import 'package:example/pages/tourist_details_page.dart';
import 'package:flutter/material.dart';
import 'package:example/models/tourist_places_model.dart' as tp;
import '../models/tourist_places_model.dart';
import '../pages/round_details_page.dart';

class TouristPlaces extends StatelessWidget {
  TouristPlaces({Key? key}) : super(key: key);


  final List<TouristPlace> beachDetails = [
    TouristPlace(
      id: '38',
      name: 'Belle Mare Beach',
      image: 'assets/beach/beach.jpg',
      description: 'Top ways to experience Belle Mare Beach: Private & Exclusive Walk, The East Splash & Fun Waterpark with 3 Watersport Activities in Belle Mare, 60-Minute Private Vacation Photopgraphy Session with Photographer in Mauritius, The Adventure East of Mauritius: 3-Watersport Activities & Blue Bay Marine Park',
      subtitle: '',
      price: '-',
      location: '',
      rating: '4.8',
      duration: 'east',
      image1: 'assets/beach/beach1.jpg',
      image2: 'assets/beach/beach2.jpg',
      image3: 'assets/beach/beach3.jpg',
      image4: 'assets/beach/beach4.jpg',
      image5: 'assets/beach/beach5.jpg',
      distance: '',
    ),
    TouristPlace(
      id: '39',
      name: 'Flic en Flac Beach',
      image: 'assets/beach/beachb.jpg',
      description: 'Hike along rocky cliffs to this pristine, uncrowded beach tucked between two jagged cliffs on the earstern side of Rodrigues Island.',
      subtitle: '',
      price: '-',
      location: '-',
      rating: '4.2',
      duration: 'south',
      image1: 'assets/beach/beach6.jpg',
      image2: 'assets/beach/beach7.jpg',
      image3: 'assets/beach/beach8.jpg',
      image4: 'assets/beach/beach9.jpg',
      image5: 'assets/beach/beach10.jpg',
      distance: '',
    ),
    TouristPlace(
      id: '40',
      name: 'Pointe D\'Esny Beach',
      image: 'assets/beach/beachc.jpg',
      description: 'Escape the Blue Bay beach frenzy and visit this hidden pearl on the outskirts of south Mahébourg. Pointe d’esny beach is one of the best kept secrets of the East coast beaches in Mauritius.',
      subtitle: '',
      price: '-',
      location: '-',
      rating: '3.2',
      duration: 'south',
      image1: 'assets/beach/beach11.jpg',
      image2: 'assets/beach/beach12.jpg',
      image3: 'assets/beach/beach13.jpg',
      image4: 'assets/beach/beach14.jpg',
      image5: 'assets/beach/beach15.jpg',
      distance: '',
    ),
    TouristPlace(
      id: '41',
      name: 'Mont Choisy Beach',
      image: 'assets/beach/beachd.jpg',
      description: 'Top ways to experience Mont Choisy Beach: Snorkelling with Giant Turtles & Beach Hopping in the North, Swim with Wild Dolphins',
      subtitle: '',
      price: '',
      location: '',
      rating: '4.7',
      duration: 'north',
      image1: 'assets/beach/beach16.jpg',
      image2: 'assets/beach/beach17.jpg',
      image3: 'assets/beach/beach18.jpg',
      image4: 'assets/beach/beach19.jpg',
      image5: 'assets/beach/beach20.jpg',
      distance: '',
    ),
    TouristPlace(
      id: '42',
      name: 'Le Morne Beach',
      image: 'assets/beach/beache.jpg',
      description: 'Le Morne beach is located on a peninsula on the west coast of Mauritius at the foot of the majestic Morne Brabant mountain listed as the World Heritage by the Unesco. The public beach of Le Morne is easily accessible from the coastal road. Le Morne beach is a beautiful beach with miles of white sand with large casuarina trees surrounded by a crystal clear water offering great visibility ideal for scuba diving and Le Morne mountain as a backdrop. A beautiful setting known as the best kite surfing spot of Mauritius, some go further and say that Le Morne is one of the best spot in the world.',
      subtitle: '',
      price: '-',
      location: '-',
      rating: '4.6',
      duration: 'south',
      image1: 'assets/beach/beach21.jpg',
      image2: 'assets/beach/beach22.jpg',
      image3: 'assets/beach/beach23.jpg',
      image4: 'assets/beach/beach24.jpg',
      image5: 'assets/beach/beach25.jpg',
      distance: '',
    ),

  ];
  final List<TouristPlace> foodDetails = [
    TouristPlace(
      id: '43',
      name: 'Creole Shack',
      image: 'assets/food/fooda.jpg',
      description: 'Reservations, Outdoor Seating, Seating, Wheelchair Accessible, Serves Alcohol, Free Wifi, Table Service, Street Parking, Free off-street parking, Wine and Beer',
      subtitle: '',
      price: '',
      location: '',
      rating: '4.6',
      duration: 'south',
      image1: 'assets/food/food1.jpg',
      image2: 'assets/food/food2.jpg',
      image3: 'assets/food/food3.jpg',
      image4: 'assets/food/food4.webp',
      image5: 'assets/food/food5.webp',
      distance: '',
    ),
    TouristPlace(
      id: '44',
      name: 'Bodrum Blue',
      image: 'assets/food/food6.jpg',
      description: 'This Authentic Turkish restaurant on its own mini peninsula creates Levantine mezzes and succulent kebabs with authentic cuisine inspired by Bodrum’s convivial coastline and Turkey’s vibrant capital. Evenings are spent dining surrounded on all sides by the lapping waters of the lagoon and cooling sea breezes of the Indian Ocean. Expect fresh flavours from our Turkish chefs and the freshest weekly',
      subtitle: '',
      price: '',
      location: '',
      rating: '5',
      duration: 'north',
      image1: 'assets/food/food6.jpg',
      image2: 'assets/food/food7.jpg',
      image3: 'assets/food/food8.jpg',
      image4: 'assets/food/food9.jpg',
      image5: 'assets/food/food10.jpg',
      distance: '',
    ),
    TouristPlace(
      id: '45',
      name: 'Table d\'hôte Chez Mamie Sophie',
      image: 'assets/food/food11.jpg',
      description: 'This Authentic Turkish restaurant on its own mini peninsula creates Levantine mezzes and succulent kebabs with authentic cuisine inspired by Bodrum’s convivial coastline and Turkey’s vibrant capital. Evenings are spent dining surrounded on all sides by the lapping waters of the lagoon and cooling sea breezes of the Indian Ocean. Expect fresh flavours from our Turkish chefs and the freshest weekly',
      subtitle: '',
      price: '',
      location: '',
      rating: '5',
      duration: 'East',
      image1: 'assets/food/food11.jpg',
      image2: 'assets/food/food12.jpg',
      image3: 'assets/food/food13.jpg',
      image4: 'assets/food/food14.jpg',
      image5: 'assets/food/food15.jpg',
      distance: '',
    ),
    TouristPlace(
      id: '46',
      name: 'Sitar Indian Restaurant',
      image: 'assets/food/food16.webp',
      description: 'At Sitar our preparations include a mix of spices which is a century-old craft of India\'s King Dynasty, as well as more recent recipes from the Maharaja\'s very own kitchen. Discover our rich variety of north Indian cuisine prepared by Chefs trained in some of best hotels in India. Our Chef is famous throughout India for his expertise in preparing exquisite Indian dishes with their original taste and savour... the difference is in the taste! We look forward to welcome you at Sitar.',
      subtitle: '',
      price: '',
      location: '',
      rating: '4.2',
      duration: 'center',
      image1: 'assets/food/food16.webp',
      image2: 'assets/food/food17.webp',
      image3: 'assets/food/food18.jpg',
      image4: 'assets/food/food19.jpg',
      image5: 'assets/food/food20.jpg',
      distance: '',
    ),
    TouristPlace(
      id: '47',
      name: 'Le Château De Bel Ombre',
      image: 'assets/food/food21.webp',
      description: 'Embark on a culinary journey with the finest ingredients and recipes, discovering the story of our vibrant culture by celebrating Mauritian elegance and the Bel Ombre ‘’Art de vivre’’. And since we are talking about the art of living: what better reflection is there of a region than its terroir? The sophisticated cuisine combines farm-to-fork dining with locavorism, a gourmet celebration of local produce. One thing is for sure: Le Château de Bel Ombre cannot be described, it can only be experienced… ',
      subtitle: '',
      price: '',
      location: '',
      rating: '4.8',
      duration: 'south',
      image1: 'assets/food/food21.webp',
      image2: 'assets/food/food22.webp',
      image3: 'assets/food/food23.jpg',
      image4: 'assets/food/food24.jpg',
      image5: 'assets/food/food25.jpg',
      distance: '',
    ),
  ];
  final List<TouristPlace> islandDetails = [
    TouristPlace(
      id: '48',
      name: 'Ile aux Cerfs',
      image: 'assets/island/island.jpg',
      description: 'The Ile aux Cerfs Leisure Island lies off Trou d\'Eau Douce in the largest lagoon of Mauritius and offers picturesque surroundings in a "chic and wild" setting for a breathtaking experience of natural beauty. It is home to beach restaurants, an adventure park, a wide array of water sports and an 18-hole golf course as well as untouched tranquil beaches.',
      subtitle: '',
      price: '',
      location: '',
      rating: '4.3',
      duration: 'east',
      image1: 'assets/island/island1.jpg',
      image2: 'assets/island/island2.jpg',
      image3: 'assets/island/island3.jpg',
      image4: 'assets/island/island4.jpg',
      image5: 'assets/island/island5.jpg',
      distance: '',
    ),
    TouristPlace(
      id: '49',
      name: 'Ile aux Aigrettes Nature Reserve',
      image: 'assets/island/island6.jpg',
      description: 'Ile aux Aigrettes is a small (27 ha) island situated in the Mahebourg Bay, about 850 m off the south-east coast of Mauritius. Unlike the mainland which is of volcanic origin, Ile aux Aigrettes is made up of coralline limestone. It is home to the last remnants of dry coastal forest, once found around most of Mauritius. Like the mainland, Ile aux Aigrettes was affected by tree logging and land clearance, and the introduction of exotic animal and plant species almost destroyed the native fauna and flora. In 1965 the island was declared a nature reserve and our intense conservation efforts have resulted in the restoration of the forest and reintroduction of rare species that had long since disappeared from the island.',
      subtitle: '',
      price: '',
      location: '',
      rating: '4.1',
      duration: 'south',
      image1: 'assets/island/island6.jpg',
      image2: 'assets/island/island7.jpg',
      image3: 'assets/island/island8.jpg',
      image4: 'assets/island/island9.jpg',
      image5: 'assets/island/island10.jpg',
      distance: '',
    ),
    TouristPlace(
      id: '50',
      name: 'Ile des Deux Cocos',
      image: 'assets/island/island11.jpg',
      description: 'Whoever said life is about the journey, not the destination, probably didn\'t own a private tropical island retreat. Between the unobstructed views, a picturesque villa and the team of dedicated staff, you can pretty much live out your ultimate castaway fantasy on Île des Deux Cocos. This beautiful jewelled pendant in a turquoise ocean lies just off the south east coast of Mauritius. Reserve this island resort in Mauritius for an overnight stay, visit for day trips, or host your own exclusive party or special event, including weddings and anniversaries.',
      subtitle: '',
      price: '',
      location: '',
      rating: '4',
      duration: 'south-east',
      image1: 'assets/island/island11.jpg',
      image2: 'assets/island/island12.jpg',
      image3: 'assets/island/island13.jpg',
      image4: 'assets/island/island14.jpg',
      image5: 'assets/island/island15.jpg',
      distance: '',
    ),
    TouristPlace(
      id: '51',
      name: 'Ile des Cocos',
      image: 'assets/island/island16.jpg',
      description: 'L\'ile aux cocos est une reserve d\'oiseaux bordée de sable blanc et de mer turquoise. En été des milliers d\'oiseaux marins y pondent . In lieu idyllique certe mais préservée comme un trésor...',
      subtitle: '',
      price: '',
      location: '',
      rating: '4',
      duration: 'west',
      image1: 'assets/island/island16.jpg',
      image2: 'assets/island/island17.jpg',
      image3: 'assets/island/island18.jpg',
      image4: 'assets/island/island19.jpg',
      image5: 'assets/island/island20.jpg',
      distance: '',
    ),
    TouristPlace(
      id: '52',
      name: 'Cat Island (Ile aux chats)',
      image: 'assets/island/island21.jpg',
      description: 'L’île aux Chats est réputée pour ses sites de plongée en apnée et avec bouteilles. Cette île se trouve dans le vaste lagon aux eaux cristallines dans lequel vous pourrez profiter des fonds marins multicolores.',
      subtitle: '',
      price: '',
      location: '',
      rating: '4',
      duration: 'south',
      image1: 'assets/island/island21.jpg',
      image2: 'assets/island/island22.jpg',
      image3: 'assets/island/island23.jpg',
      image4: 'assets/island/island24.jpg',
      image5: 'assets/island/island25.jpg',
      distance: '',
    ),
  ];
  final List<TouristPlace> mallDetails = [
    TouristPlace(
      id: '53',
      name: 'Bagatelle Mall by Ascencia',
      image: 'assets/mall/mall1.jpg',
      description: 'Bagatelle Mall is the leading shopping and retail destination in Mauritius. Its dominant presence and comprehensive retail and leisure options attract diverse shoppers from all over the island. Bagatelle Mall merges the world\'s most desirable brands, shopping convenience, entertainment, and everyday leisure, all in a majestic setting. Bagatelle Mall hosts the widest selection of specialty stores in Mauritius - there are 155 shops - thus offering the most comprehensive and compelling lifestyle shopping experience on the island. The spacious Food Court also gives hungry shoppers plenty of mouthwatering options.',
      subtitle: '',
      price: '-',
      location: '-',
      rating: '4.7',
      duration: 'Center',
      image1: 'assets/mall/mall1.jpg',
      image2: 'assets/mall/mall2.jpg',
      image3: 'assets/mall/mall3.jpg',
      image4: 'assets/mall/mall4.jpg',
      image5: 'assets/mall/mall5.jpg',
      distance: '',
    ),
    TouristPlace(
      id: '54',
      name: 'Cascavelle Shopping Mall',
      image: 'assets/mall/mall6.jpg',
      description: 'Cascavelle Shopping Mall has been developed by Medine Property in 2011. This 12,000m² shopping precinct is open seven days a week and offers a lively and vibrant open-air setting with airy patios, stunning views on the sea and mountains, in a lush environment. This one stop shop of the West of Mauritius offers unique and pleasant shopping experience with some 60 outlets including supermarket, clothing, footwear, jewelry, childcare, sports and home decoration complemented by a new attractive food court with various eateries.',
      subtitle: '',
      price: '',
      location: '-',
      rating: '4.8',
      duration: 'south',
      image1: 'assets/mall/mall6.jpg',
      image2: 'assets/mall/mall7.jpg',
      image3: 'assets/mall/mall8.jpg',
      image4: 'assets/mall/mall9.jpg',
      image5: 'assets/mall/mall10.jpg',
      distance: '',
    ),
    TouristPlace(
      id: '55',
      name: 'Phoenix Mall',
      image: 'assets/mall/mall11.jpg',
      description: 'Phoenix Mall is the perfect venue should you be looking for shopping, food, entertainment or a fun family outing. With more than 70 shops, the mall offers a glorious shopping experience. From leading local retailers to world famous international brands and through the diversified food outlets, Phoenix Mall remains the one-stop destination fro your shopping indulgences and excellent food.',
      subtitle: '',
      price: '',
      location: '-',
      rating: '4.7',
      duration: 'center',
      image1: 'assets/mall/mall11.jpg',
      image2: 'assets/mall/mall12.jpg',
      image3: 'assets/mall/mall13.jpg',
      image4: 'assets/mall/mall14.jpg',
      image5: 'assets/mall/mall15.jpg',
      distance: '',
    ),
    TouristPlace(
      id: '56',
      name: 'Trianon Shopping Park',
      image: 'assets/mall/mall16.jpg',
      description: 'Situated in the heart of Mauritius, La City Trianon is a convenient place to come for the shopping and entertaining pastime from different parts of the island. It is a one-stop-destination for anyone looking for a comfortable and stylish place to enjoy the best shopping conditions on a GLA – Gross Leasable Area of 23,000 m2 and a variety of fun options for children and adults. The shopping mall’s outdoor parking has a capacity of 1000 cars, and the basement parking can accommodate up to 200 cars. Currently, La City Trianon can be portrayed as a destination of choice that offers an incomparable variety of more than 100 stores including clothing and shoe stores, food court with 17 locations, modern cinema that provides an unbeatable movie experience, an amusement park for children, and a lot more.',
      subtitle: '',
      price: '',
      location: '-',
      rating: '4.8',
      duration: 'center',
      image1: 'assets/mall/mall16.jpg',
      image2: 'assets/mall/mall17.jpg',
      image3: 'assets/mall/mall18.jpg',
      image4: 'assets/mall/mall19.jpg',
      image5: 'assets/mall/mall20.jpg',
      distance: '',
    ),
    TouristPlace(
      id: '57',
      name: 'Grand Baie La Croisette',
      image: 'assets/mall/mall21.jpg',
      description: 'Imagine a place where pleasure meets the practical: a place to indulge in one’s favourite workout, relax in a trendy coffee shop or enjoy a lunch break, meet with friends to view the latest movie, do your groceries or go ‘treasure hunting’ in one of the several outlets of the shopping mall while also attending to your bank transactions . . . Welcome to La Croisette ! Everything at La Croisette has been geared towards introducing a totally new lifestyle experience to its visitors. The 104 brands (shops & restaurants) in the Mall have been carefully selected based on their brand appeal as well as on the merit of diversity. The mall also harbours other activity zones: residential, office, movie theater, hypermarket, financial institutions and sports & wellness centre. Leisure activities take a good share of the mall with a public esplanade that come alive during the many events planned throughout the year . . . See you soon !',
      subtitle: '',
      price: '',
      location: '-',
      rating: '4.9',
      duration: 'north',
      image1: 'assets/mall/mall21.jpg',
      image2: 'assets/mall/mall22.jpg',
      image3: 'assets/mall/mall23.jpg',
      image4: 'assets/mall/mall24.jpg',
      image5: 'assets/mall/mall25.jpg',
      distance: '',
    ),
  ];
  final List<TouristPlace> hotelDetails = [
    TouristPlace(
      id: '58',
      name: 'Salt Of Palmar, Mauritius, A member Of Design Hotels',
      image: 'assets/hotel/hotel1.jpg',
      description: 'An adult-only boutique hotel in Mauritius for lovers of design, food, travel, and all things local. We believe in meaningful travel. That’s travel that takes you to people, not just places. Meaningful travel satisfies curiosity and connects you to the local community and their way of life. You’re listening to and tasting local. You’re out there exploring. You’re in it, not beside it. SALT of Palmar is a beautiful base that not just give you everything you need to discover Mauritius. But also everything you need to relax, escape, and recharge. Even better, you’re involved in a good thing. We give back to the local communities we are part of and do all we can to protect their environments. Sustainability starts there. We boost economies by employing, sourcing, and collaborating locally. Our food philosophy is fresh, local, homegrown, homemade and no waste. We keep it simple. We remove the obstacles to your being in the place you’re in. That’s luxury in our book. It’s all about inspiration, adventure, and positive impact.',
      subtitle: '',
      price: '',
      location: '-',
      rating: '5',
      duration: 'east',
      image1: 'assets/hotel/hotel1.jpg',
      image2: 'assets/hotel/hotel2.jpg',
      image3: 'assets/hotel/hotel3.jpg',
      image4: 'assets/hotel/hotel4.jpg',
      image5: 'assets/hotel/hotel5.jpg',
      distance: '',
    ),
    TouristPlace(
      id: '59',
      name: 'Constance Belle Mare Plage',
      image: 'assets/hotel/hotel6.jpg',
      description: 'Soft white sand, blue sky dotted with white clouds and turquoise lagoon which beckons long soaks… Stylishly renovated Constance Belle Mare Plage offers comfortable accommodations in a lively and cosy atmosphere; choose from one of the 104 Prestige Rooms, 149 Junior Suites, 6 Deluxe Suites, 18 distinctive Villas or the Presidential Villa for a top-notch island holiday. Seize the opportunity to try new things while having fun. Whether it’s relaxing on the beach or at one of the trendy bars, working out at the gym, pampering at the spa or enjoying water sports, Constance Belle Mare Plage is for an exciting memorable break! Seven distinctive restaurants and six hip bars situated at prime locations await you. And if you are staying with your kids, you will be thrilled to know that they will be having their share of adventures and fun too, at the Constance Kids Club. Set along a stunning 2km white sand beach, in a sheltered bay on the east coast of Mauritius, Constance Belle Mare Plage is a harmonious combination of tropical environment and Constance Chic. Combining space and design, all rooms are thoughtfully furnished and decorated for your comfort. Inspired by the unique beauty of the East Coast; space and style were combined to create comfort, to radiate brightness and to breathe in the freshness of the Indian Ocean.',
      subtitle: '',
      price: '',
      location: '-',
      rating: '5',
      duration: 'East',
      image1: 'assets/hotel/hotel6.jpg',
      image2: 'assets/hotel/hotel7.jpg',
      image3: 'assets/hotel/hotel8.jpg',
      image4: 'assets/hotel/hotel9.jpg',
      image5: 'assets/hotel/hotel10.jpg',
      distance: '',
    ),
    TouristPlace(
      id: '60',
      name: 'Tamassa Resort',
      image: 'assets/hotel/hotel11.jpg',
      description: 'A new experience awaits guests at this beautiful all-inclusive beach hotel in Mauritius, located in Bel Ombre, on the island\'s south-west coast. Tamassa, a 4-star beach hotel, stands at the end of a long avenue of mature coconut palms towering skywards. A picture postcard landscape stretches across sugarcane fields to the mountains beyond. The south-west is a beautiful part of Mauritius, with spectacular walks and drives through lush, tropical hillsides and a range of open-air activities in beautiful countryside. In front of the beach hotel, beyond the sandy beach, lies a turquoise lagoon that almost blends into the skyline. The sea air is invigorating and the ripples of the waves gently calming. Beyond, lie thousands of miles of open sea. The traditional style architecture ideally suits the tropical setting, with beautifully landscaped gardens. The buildings seem at one with the environment. The decor is breathtakingly contemporary, with clean lines and bold use of colour. The atmosphere is one of eternal youth, friendly, cheerful and enthusiastic. Tamassa is a new Mauritian experience!',
      subtitle: '',
      price: '',
      location: '-',
      rating: '5',
      duration: 'South',
      image1: 'assets/hotel/hotel11.jpg',
      image2: 'assets/hotel/hotel12.jpg',
      image3: 'assets/hotel/hotel13.jpg',
      image4: 'assets/hotel/hotel14.jpg',
      image5: 'assets/hotel/hotel15.jpg',
      distance: '',
    ),
    TouristPlace(
      id: '61',
      name: 'The Westin Turtle Bay Resort & Spa, Mauritius',
      image: 'assets/hotel/hotel16.jpg',
      description: 'At The Westin Turtle Bay Resort Spa, Mauritius, we know that feeling good flows naturally from unwinding in a delightfully comfortable environment. Our mission is to take care of everything down to the smallest detail to make sure you leave wonderfully rested, well-nourished and nurtured. Step into our world, let it become yours, and treat yourself to tranquility. Spacious yet luxuriously cosy, our rooms feature the Heavenly Beds and Heavenly Bath which promise a great holiday. Every aspect of the Resort experience is designed with travelers’ well-being in mind, ensuring that guests leave feeling better than when they arrived. The Heavenly Spa indulge guests in elements of well-being. Eat, drink and relax in style with our choice of 5 restaurants, each carefully designed to stimulate your tastebuds with our fresh and delicious healthy produce. Allow yourself to unwind in a cool relaxing interior or the lush and invigorating great outdoors, while we treat you royally.',
      subtitle: '',
      price: '',
      location: '-',
      rating: '5',
      duration: 'west',
      image1: 'assets/hotel/hotel16.jpg',
      image2: 'assets/hotel/hotel17.jpg',
      image3: 'assets/hotel/hotel18.jpg',
      image4: 'assets/hotel/hotel19.jpg',
      image5: 'assets/hotel/hotel20.jpg',
      distance: '',
    ),
    TouristPlace(
      id: '62',
      name: 'LUX Grand Gaube Resort & Villas',
      image: 'assets/hotel/hotel21.jpg',
      description: 'A work of art by the renowned interior designer Kelly Hoppen and leading Mauritian architect - Jean Francois Adam, LUX* Grand Gaube is a retro-chic tropical resort in the north of Mauritius. Tucked away on a peninsula bordering two coves, the eclectic lifestyle resort blends perfectly with the surrounding tropical greenery and is blessed with two tranquil beaches and two spectacular swimming pools. LUX* Grand Gaube offers a unique dining experience with its 6 restaurants and 8 bars. A global culinary journey leads to live cooking stations at The Palm Court, Peruvian and Argentinian cuisine at INTI, authentic Creole flavors at Banyan, and a Turkish twist at Bodrum Blue. Add our famous Café LUX, the Beach Rouge dining club plus a host of surprises at every turn - the resort living has never looked or tasted so good! With an easy living, smile-inducing personality - LUX Grand Gaube is the best of every world.',
      subtitle: '',
      price: '',
      location: '-',
      rating: '5',
      duration: 'North',
      image1: 'assets/hotel/hotel21.jpg',
      image2: 'assets/hotel/hotel22.jpg',
      image3: 'assets/hotel/hotel23.jpg',
      image4: 'assets/hotel/hotel24.jpg',
      image5: 'assets/hotel/hotel25.jpg',
      distance: '',
    ),
  ];

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 40,
      child: ListView.separated(
        physics: const BouncingScrollPhysics(),
        scrollDirection: Axis.horizontal,
        itemBuilder: (context, index) {
          final tp.RoundTouristPlace touristPlace = touristPlaces[index];
          return GestureDetector(
            onTap: () {
              if (index == 0) {
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) => roundDetailsPage(placeList: beachDetails),
                  ),
                );
              } else if (index == 1) {
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) => roundDetailsPage(placeList: foodDetails),
                  ),
                );
              } else if (index == 2) {
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) => roundDetailsPage(placeList: islandDetails),
                  ),
                );
              } else if (index == 3) {
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) => roundDetailsPage(placeList: mallDetails),
                  ),
                );
              } else if (index == 4) {
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) => roundDetailsPage(placeList: hotelDetails),
                  ),
                );
              }
            },
            child: Chip(
              label: Text(touristPlace.name),
              avatar: CircleAvatar(
                backgroundImage: AssetImage(touristPlace.image),
              ),
              backgroundColor: Colors.white,
              elevation: 1,
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
            ),
          );
        },
        separatorBuilder: (context, index) => const Padding(padding: EdgeInsets.only(right: 10)),
        itemCount: touristPlaces.length,
      ),
    );
  }
}
